[model]
    name    = "Ising"

    [model.graph]
    name   = "recursive_tree"
    settings = {r = 3, jump = 0}




[simulation]
    [simulation.snapshots]
        n_samples = 100

    [simulation.conditional]
        repeats = 1000
        time_steps = 2
