output_directory = "experiments_test"
experiment_run   = "experiment_configs/Potts_recursion1.py"
name = "tipping_points"

[model]
    name       = "Potts"
    sampleSize = 1
    [model.graph]
        name     = "recursive_tree"
        settings = {r = 4, jump = 0}

[simulation]
    trials = 10
    # simulations parameters
    [simulation.tipping]
        n_samples   = 10
        buffer_size = 10
        surround    = 1
        sigma       = 100

    [simulation.conditional]
        repeats    = 10000
        time_steps = 10
