output_directory = "/var/scratch/cveltere/"
experiment_run   = "experiment_configs/Potts_recursion1.py"
name = "tipping_points"

[model]
    name       = "Potts"
    [model.settings]
        sampleSize = 1
    [model.graph]
        name     = "recursive_tree"
        settings = {r = 10, jump = 0}

[simulation]
    trials = 10
    # simulations parameters
    [simulation.tipping]
        n_samples   = 100
        buffer_size = 100000000
        surround    = 1000
        sigma       = 100

    [simulation.conditional]
        repeats    = 10000
        time_steps = 400
