# output_directory = "/var/scratch/cveltere/"
output_directory = "data/"
experiment_run   = "experiment_configs/Potts_recursion1.py"
name             = "tipping_points"

[model]
    name       = "Potts"
    [model.settings]
        sampleSize = 1
    [model.graph]
        name     = "recursive_tree"
        settings = {r = 3, jump = 0}

[simulation]
    trials = 10
    # simulations parameters
    [simulation.tipping]
        n_samples   = 1
        buffer_size = 100000
        surround    = 1000
        sigma       = 10

    [simulation.conditional]
        repeats    = 10
        time_steps = 40
