# experiment_run = "configs/Potts_recursion_center_focus.py"
# experiment_run = 'configs/Potts_recursion1.py'
# experiment_run = 'configs/powerlaw_graph.py'

# trials = 1

[general]
    # simulations parameters
    trials = 1
    [general.tipping]
        n_samples     = 100
        buffer_size   = 1000000
        surround      = 10000
        reset         = false

    [general.snapshots]
      n_samples = 10000
      step      = 1
    
    [general.conditional]
        repeats    = 1000
        time       = 100

[sbatch]
  cpus-per-task    = 1  
  ntasks-per-node  = 1
  cores-per-socket = 16
  constraint       = "cpunode"
  # output           = "%x-$j."
  # error            = "%x-%j.err"
  deadline         = "48:00:00"

# experiments to run
[experiments]
#[experiments.tipping]
#[experiments.tipping2]
# [experiments.kite]
#[experiments.psycho]
# [experiments.dummy]
[experiments.valuenetwork_annealing]
# [experiments.value_network_satisfaction]
# [experiments.value_stability]
