# output_directory = "data/"
output_directory = "/var/scratch/cveltere/"
# experiment_run   = "experiment_configs/Potts_recursion_center_focus.py"
experiment_run = 'experiment_configs/Potts_recursion1.py'

trials = 10
[model]
    name       = "Potts"
    [model.settings]
        sampleSize = 1
    [model.graph]
        name     = "recursive_tree"
        settings = {r = 5, jump = 0}

[simulation]
    # simulations parameters
    [simulation.tipping]
        n_samples   = 1000
        buffer_size = 1000000
        surround    = 10
        start       = 3
        sigma       = 1000

    [simulation.conditional]
        repeats    = 10000
        time_steps = 1000
