# local tests
# output_directory = "data/"
# server
output_directory = "/var/scratch/cveltere/"

# runs
# experiment_run = "configs/Potts_recursion_center_focus.py"
# experiment_run = 'configs/Potts_recursion1.py'
experiment_run = 'configs/powerlaw_graph.py'

trials = 1
[model]
    name       = "Potts"
    [model.settings]
        sampleSize = 1
    [model.graph]
        # name     = "recursive_tree"
        name = "graph.powerlaw_graph"
        settings = {n = 30, gamma = 1.6}
        # settings = {r = 5, jump = 0}

[simulation]
    # simulations parameters
    [simulation.tipping]
        n_samples   = 10
        buffer_size = 10000
        window      = 100
        asymmetric  = true
        spacing     = 1
        rtol        = 0.05

    [simulation.conditional]
        repeats    = 1000
        time_steps = 100
