# output_directory = "/var/scratch/cveltere/"
output_directory = "/var/scratch/cveltere/"
# experiment_run   = "experiment_configs/Potts_recursion_center_focus.py"
experiment_run = 'experiment_config/Potts_recursion1.py'

trials = 10
[model]
    name       = "Potts"
    [model.settings]
        sampleSize = 1
    [model.graph]
        name     = "recursive_tree"
        settings = {r = 6, jump = 0}

[simulation]
    # simulations parameters
    [simulation.tipping]
        n_samples   = 100
        buffer_size = 10000000
        surround    = 1000
        sigma       = 100

    [simulation.conditional]
        repeats    = 10000
        time_steps = 1000
