# output_directory = "/var/scratch/cveltere/"
output_directory = "/var/scratch/cveltere/"
experiment_run   = "experiment_configs/Potts_recursion1.py"

trials = 100
[model]
    name       = "Potts"
    [model.settings]
        sampleSize = 1
    [model.graph]
        name     = "recursive_tree"
        settings = {r = 20, jump = 0}

[simulation]
    # simulations parameters
    [simulation.tipping]
        n_samples   = 50
        buffer_size = 1000000
        surround    = 1000
        sigma       = 100

    [simulation.conditional]
        repeats    = 1000
        time_steps = 400
