# local tests
# server

# runs
# experiment_run = "configs/Potts_recursion_center_focus.py"
# experiment_run = 'configs/Potts_recursion1.py'
experiment_run = 'configs/powerlaw_graph.py'

trials = 1
[model]
    name       = "Potts"
    [model.settings]
        sampleSize = 1
    [model.graph]
        # name     = "recursive_tree"
        name = "graph.powerlaw_graph"
        settings = {n = 30, gamma = 1.1}
        # settings = {r = 5, jump = 0}

[simulation]
    # simulations parameters
    [simulation.tipping]
        n_samples   = 500
        buffer_size = 10000
        window      = 1000
        asymmetric  = false
        spacing     = 1

    [simulation.conditional]
        repeats    = 1000
        time_steps = 1000
