output_directory = "/var/scratch/cveltere/"
# output_directory = "experiments"
experiment_run   = "experiment_configs/Potts_recursion1.py"
name = "tipping_points"

[model]
    name       = "Potts"
    [model.settings]
        sampleSize = 1
    [model.graph]
        name     = "recursive_tree"
        settings = {r = 5, jump = 0}

[simulation]
    trials = 10
    # simulations parameters
    [simulation.tipping]
        n_samples   = 100
        buffer_size = 10
        surround    = 1
        sigma       = 100

    [simulation.conditional]
        repeats    = 100
        time_steps = 40
